# Generated by Django 5.1.4 on 2025-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section_bg_photo', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
        ),
    ]
