# Generated by Django 5.1.4 on 2025-02-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_section_subtitle',
            new_name='hero_section_heading',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_section_title',
            new_name='hero_section_subheading',
        ),
    ]
