# Generated by Django 5.1.4 on 2025-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
