# Generated by Django 5.1.4 on 2025-02-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_hero_section_subtitle_homepage_hero_section_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_cta_btn_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
