# Generated by Django 5.1.4 on 2025-01-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rescuecategory_adoptablerescue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticlecategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='newsarticlecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
