# Generated by Django 5.1.4 on 2025-01-26 18:10

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_googleform_rescuecategory_adoptablerescue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptableRescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/')),
                ('additional_picture_1', models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/')),
                ('additional_picture_2', models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/')),
                ('additional_picture_3', models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/')),
                ('additional_picture_4', models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.rescuecategory')),
            ],
        ),
    ]
