# Generated by Django 5.1.4 on 2025-01-26 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rescuecategory_adoptablerescue'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptablerescue',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
