# Generated by Django 5.1.4 on 2025-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_newsarticlecategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
