# Generated by Django 5.1.4 on 2025-02-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_homepage_hero_section_cta_btn_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_us_section_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
