# Generated by Django 5.1.4 on 2025-01-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_homepage_hero_section_bg_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelibrary',
            name='name',
        ),
    ]
