# Generated by Django 5.1.4 on 2025-02-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_homepage_about_us_section_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_section_cta_btn_text',
        ),
    ]
