# Generated by Django 5.1.4 on 2025-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_imagelibrary_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageLibrary',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_section_bg_photo',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
    ]
