# Generated by Django 5.1.4 on 2025-01-26 14:29

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_newsarticle_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
