# Generated by Django 5.1.4 on 2025-01-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_adoptablerescue_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptablerescue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.rescuecategory'),
        ),
    ]
