# Generated by Django 5.1.4 on 2025-01-22 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_delete_imagelibrary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_section_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
