# Generated by Django 5.1.4 on 2025-02-17 03:53

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_homepage_hero_section_cta_btn_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section_bg_photo', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('hero_section_heading', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('hero_section_subheading', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
