# Generated by Django 5.1.4 on 2025-01-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_adoptablerescue_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptablerescue',
            old_name='picture',
            new_name='profile',
        ),
    ]
