# Generated by Django 5.1.4 on 2025-02-17 04:19

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_homepagehero_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_section_photo', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('about_us_section_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
