# Generated by Django 5.1.4 on 2025-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_rename_picture_adoptablerescue_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptablerescue',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
