# Generated by Django 5.1.4 on 2025-01-22 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_homepage_hero_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_section_cta_btn_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_section_subtitle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
