# Generated by Django 5.1.4 on 2025-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_homepageaboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomaPageVMGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_photo', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('goal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
