# Generated by Django 5.1.4 on 2025-02-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_homapagevmgo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomaPageVMGO',
            new_name='HomePageVMGO',
        ),
    ]
