# Generated by Django 5.1.4 on 2025-01-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
