# Generated by Django 5.1.4 on 2025-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_newsarticle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptableRescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='rescues_pics/')),
            ],
        ),
    ]
