# Generated by Django 5.1.4 on 2025-02-25 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
