# Generated by Django 5.1.4 on 2025-02-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_shelter_created_at_shelter_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
