# Generated by Django 5.1.4 on 2025-01-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_adoptablerescue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='adoptablerescue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='rescues_pics/'),
        ),
        migrations.AlterField(
            model_name='adoptablerescue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.rescuecategory'),
        ),
    ]
