# Generated by Django 5.1.4 on 2025-02-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_shelter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/gallery/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/gallery/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/gallery/'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='shelters/gallery/'),
        ),
    ]
