# Generated by Django 5.1.4 on 2025-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_rescuecategory_alter_adoptablerescue_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptablerescue',
            name='additional_picture_1',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/'),
        ),
        migrations.AddField(
            model_name='adoptablerescue',
            name='additional_picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/'),
        ),
        migrations.AddField(
            model_name='adoptablerescue',
            name='additional_picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/'),
        ),
        migrations.AddField(
            model_name='adoptablerescue',
            name='additional_picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/additional/'),
        ),
        migrations.AlterField(
            model_name='adoptablerescue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_rescues/'),
        ),
    ]
