# Generated by Django 5.1.4 on 2025-01-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='in_kind_donation/'),
        ),
    ]
