# Generated by Django 5.1.4 on 2025-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_wishlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist/'),
        ),
    ]
